#!/bin/bash

set -e
NAME=${PWD##*docker-}
IMAGE_NAME=yokogawa/${NAME}
docker ps --quiet --all --filter name="${NAME}" | xargs -r docker rm >/dev/null

set -x
if [ "${1}" = "bash" ]; then
    docker run -v "${PWD}/src":/src -i -t --entrypoint="/bin/bash" --name="${NAME}" "${IMAGE_NAME}"
else
    docker run -v "${PWD}/src":/src --name="${NAME}" "${IMAGE_NAME}" $@
fi


